### ISSUE TITLE
Async component support

### ISSUE THREAD

**Issue by LeeCheneler** [afenton90/koa-react-router#10]
Any chance of getting async component support into this? 

Support for async components or guidance on how to implement them when using koa-react-router would be great. Perhaps even supports something like `getInitialProps` too?

Thoughts? Happy to help out if I can. Although my only experience of implementing async components is using bundle-loader with webpack which won't work for ssr

**Comment by afenton90** [comment]
Hey @LeeCheneler I'm so sorry its taken this long to get back to you.
If you haven't solved this problem, I'm happy to jump on a hangout or post example to show how this would work with something like https://github.com/smooth-code/loadable-components

**Comment by LeeCheneler** [comment]
Hey, my bad. I should have updated the issue when I found a solution. I use a combination of `react-jobs` and `react-async-bootrapper` and `react-async-component` 👍
