### ISSUE TITLE
Hydration incompatibilities

### ISSUE THREAD

**Issue by dtimmerman** [afenton90/koa-react-router#11]
**Problem**:

Client hydration against koa-react-router supplied HTML is not possible using option defaults.

**Example**:

```javascript
// server.js
const Container = ({ children }) => (
  <html>
    <head>...</head>
    <body>{ children }</body>
  </html>
)

const App = () => (
  <div>
    ...
  </div>
)

const app = new Koa()

app
  .use(koaReactRouter({
    App,
    onRender: () => ({ Container })
  }))
```

The HTML this produces lacks the necessary internal React data attributes that `renderToString` provides, `data-reactroot`, etc. If you attempt to `ReactDOM.hydrate()` against the server rendered HTML, hydration will fail, because of this.

Might be related to what is described in a similar problem in https://github.com/facebook/react/issues/12651. 

(react can't effectively find the root to mark, possibly related to the root within [view string](https://github.com/afenton90/koa-react-router/blob/43c8fa632629791a58d6ed36323a7f2f31451891/index.js#L30) being StaticRouter.)

This is easily circumvented by supplying an `opts.preRender` similar to below, which introduces an arbitrary practical root that renderToString can discern. A subsequent client call to `ReactDOM.hydrate` will find all the necessary react data markings it needs to hydrate against.

```javascript
const app = new Koa()

app
  .use(koaReactRouter({
    App,
    onRedirect: () => console.log('I have redirected!'),
    onRender: () => ({ Container }),
    preRender: wrapped => (
      <div id="root">
        {wrapped}
      </div>
    )
  }))
```

_NB: assume this is not within the scope of this library's design concerns. Might be worth calling out in the readme though?_

**Comment by afenton90** [comment]
Thanks @dtimmerman this is a great spot. Sorry for not getting back to you sooner. I'll take a look at re-producing this, and see if I can get a fix in or adding something to the README.

The intention is that this gives you most of what you need to do server side rendering with React Router and Koa without the need for rolling your own middleware, so if I can fix this, I'll happily release a fix.

I don't suppose you have a working example of this?
