### ISSUE TITLE
Outdated build not working for node 7 --harmony

### ISSUE THREAD

**Issue by eudaimos** [afenton90/koa-react-router#2]
I get `ReferenceError: regeneratorRuntime is not defined` error when using this package from npm using babel 6 on node 7.4 with the `--harmony` flag, meaning `async/await` are supported.

It's based on using the build output from a specific version of node.js/babel configuration as the output to the npm package distribution.

If I copy/paste the source file at [index.js](https://github.com/afenton90/koa-react-router/blob/master/index.js) into a file `/src/lib/koa-react-router/index.js` locally and `import` that, everything works.

Below is the exact output:
```bash
> node --harmony dev

/Users/jh/dev/zyzzyxlab/tao.js.example/node_modules/koa-react-router/lib/index.js:10
  onRender = _ref.onRender;return function () {var _ref2 = _asyncToGenerator(regeneratorRuntime.mark(
                                                                             ^

ReferenceError: regeneratorRuntime is not defined
    at /Users/jh/dev/zyzzyxlab/example/node_modules/koa-react-router/index.js:5:16
    at Object.<anonymous> (/Users/jh/dev/zyzzyxlab/example/src/server.js:11:9)
    at Module._compile (module.js:571:32)
    at loader (/Users/jh/dev/zyzzyxlab/example/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jh/dev/zyzzyxlab/example/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jh/dev/zyzzyxlab/example/dev.js:3:1)
```

Using this `.nvmrc` file:
```
7.4
```

Running with the following `package.json`:
```json
{
  "name": "example",
  "version": "0.0.1",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "node --harmony dev"
  },
  …
  "dependencies": {
    "koa": "^2.0.0",
    "koa-react-router": "^1.0.0",
    "react": "^15.4.2",
    "react-dom": "^15.4.2",
    "react-router": "^3.0.2"
  },
  "devDependencies": {
    "babel": "^6.5.2",
    "babel-cli": "^6.22.0",
    "babel-preset-node7": "^1.4.0",
    "babel-preset-react": "^6.22.0",
    "babel-register": "^6.18.0",
    "eslint": "^3.13.1",
    "eslint-plugin-babel": "^4.0.0"
  }
}
```

Following `.babelrc`:
```json
{
  "presets": [
    "node7",
    "react"
  ]
}
```

And the following JS files:
```javascript
// dev.js
require('babel-register');

require('./src/server');
```

```javascript
// /src/server.js
import Koa from 'koa';

// import React from 'react';
import reactrouter from 'koa-react-router';
// below works as copied from source in github repo
// import reactrouter from './lib/koa-react-router';

// example routes
import routes from './shared/routes';
// example wrapping component for HTML
import Html from './shared/containers/html';

const app = new Koa();

app.use(reactrouter({
    routes,
    onError: (ctx, err) => console.error(`We had an error, boss!`, err),
    onRedirect: (ctx, redirect) => console.log(`Supposed to redirect, boss. To:`, redirect),
    onNotFound: (ctx) => console.log(`Path NOT FOUND, boss`),
    onRender: (ctx) => ({ Container: Html }),
}));

app.use(async (ctx, next) => {
    console.log(`sending response back as:\n`, ctx.response.body);
});

app.listen(4008);
console.log('Web server ready, boss');
```

**Comment by afenton90** [comment]
I will spin the same config up locally and see if I can replicate this issue in node 7 @eudaimos

**Comment by eudaimos** [comment]
I think if you do decide a new published version is necessary, it would make sense to publish it with `@next` or `@node7` or `@async` tag to npm

Thanks @afenton90 - I'm trying to slowly piece together a koa-based isomorphic React implementation that doesn't require any other templating engine for server-side rendering (which all of the other boilerplates seem to include)

**Comment by afenton90** [comment]
Hey @eudaimos I haven't forgotten about this issue, just struggling to find some time to debug it.

What you are trying to achieve in a koa-based isomorphic React app, is indeed possible using this middleware, with a combination of webpack.
If you haven't already I would strongly recommend checking out [webpack 2](https://webpack.js.org/) it is scarily quick!

**Comment by afenton90** [comment]
@eudaimos So you are getting this error, because koa-react-router expects `babel-polyfill` to be used.
I will put this in as a `peerDependency` so this is more specific.

**Comment by tylerball** [comment]
I'm also seeing this error with babel-polyfill installed and added to my babel configuration.
