### ISSUE TITLE
Upgrading to React Router 4?

### ISSUE THREAD

**Issue by mindpivot** [afenton90/koa-react-router#3]
Hey there, any plans to upgrade this to the new React Router 4?

**Comment by afenton90** [comment]
Hey @mindpivot once react-router 4 is out of beta, or in release candidate, I will probably spin up a `next` tag in npm with react-router 4 support.
If react-router 4 does not change implementation of server side router matching the migration path should be quite straight forward.
I will keep this issue open, whilst I assess react-router 4.

**Comment by mindpivot** [comment]
thanks @afenton90! the issue I'm having using RR4 directly is how they've changed the 404 handling. now you're supposed to use a fall-through component to catch any route not handled explicitly, and that is expected to be the "404". the problem is, there doesn't seem to be any way (that I've been able to figure) with the new StaticRouter component to have the aforementioned catch-all 404 component update the context passed into the StaticRouter.

Updating the context obj is how they handle server-side redirects with the <Redirect> component but there seems to be no corollary method in a public API for doing so for anything but those redirects. (see https://reacttraining.com/react-router/#staticrouter) As you can see, the StaticRouter component has replaced the ServerRender component and at this point (it *is* still in beta) updating the context as needed outside of the Redirect component is an unknown.

**Comment by afenton90** [comment]
I haven't forgotten about this, and am currently looking at upgrading `koa-react-router` to support react-router@4. Hopefully, this should be done soon.

**Comment by devyash** [comment]
@afenton90 Do we have a timeline for the upgrade process ? I really like this project and I am thankful for your efforts to maintain this.

**Comment by archae0pteryx** [comment]
Yeah! This is awesome. Keep up the good work mang! ❤️

**Comment by afenton90** [comment]
React Router 4 support has been added in v2.0.0 of this repo. Thanks all 👍

**Comment by mindpivot** [comment]
Thanks!
